### PR TITLE
apps sc: sc-log-retention deletion fix

### LINKED ISSUE #340: SC log retention doesn't work with some S3 "compatible" implementations
**Describe the bug**
The [sc-logs-retention](https://github.com/elastisys/compliantkubernetes-apps/tree/main/helmfile/charts/sc-logs-retention) CronJob runs successfully without deleting all old logs. You can see this by checking the logs from multiple runs and notice that they remove logs from the same days. This probably only happens with some providers that have a faulty or incomplete implementation of the S3 API.

**To Reproduce**
1. Make sure there are lots of logs stored in the bucket.
2. Run the retention job, either manually or wait for it to run multiple times.
3. Compare the logs between the runs.
4. See that even though Job 1 claims to have deleted logs from day xx.yy.zzzz, Job 2 also finds and deletes logs from this day.

**Expected behavior**
The Job should remove all logs from the days outside of the retention period, not just some.

**Version (add all relevant versions):**
 - Compliant kubernetes apps version v0.9.0

**Additional context**

The problem is probably due to a faulty/not complete implementation of [list-objects-v2](https://docs.aws.amazon.com/cli/latest/reference/s3api/list-objects-v2.html).

### PR DESCRIPTION
**Pull request by robinelastisys**
**What this PR does / why we need it**:
Right now, all logs doesn't get removed at the same time which results in that the job have to be ran multiple times potentially. This is now fixed by adding a while-loop with a 5 second delay.

**Which issue this PR fixes**: 
fixes #340 

**Checklist:**

- [x] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/blob/main/WIP-CHANGELOG.md)
- [x] Proper commit message prefix on all commits
- [ ] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset backwards compatible for existing clusters? Applying:
    - [ ] is completely transparent, will not impact the workload in any way.
    - [ ] requires running a migration script.
    - [ ] will create noticeable cluster degradation.
          E.g. logs or metrics are not being collected or Kubernetes API server
          will not be responding while upgrading.
    - [ ] requires draining and/or replacing nodes.
    - [ ] will change any APIs.
          E.g. removes or changes any CK8S config options or Kubernetes APIs.
    - [ ] will break the cluster.
          I.e. full cluster migration is required.
- Chart checklist (pick exactly one):
    - [x] I upgraded no Chart.
    - [ ] I upgraded a Chart and determined that no migration steps are needed.
    - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).

### CODE REVIEW

File: helmfile/charts/sc-logs-retention/scripts/logs-retention.sh [hunk 1]
```diff
@@ -49,8 +49,17 @@ else
...
 
       echo "Deleting backup ${BACKUP_URI}"
-      aws s3 rm --recursive "${BACKUP_URI}" --endpoint-url="${S3_REGION_ENDPOINT}"
-    elif [[ ${GCS_BACKUP} == "true" ]]; then
+      NR_OF_FILES=$(aws s3 ls "${BACKUP_URI}" --endpoint-url="${S3_REGION_ENDPOINT}" | wc -l)
+      while [ "$NR_OF_FILES" -gt 0 ]; do
+        aws s3 rm --recursive "${BACKUP_URI}" --endpoint-url="${S3_REGION_ENDPOINT}"
+        sleep 5
+        NR_OF_FILES=$(aws s3 ls "${BACKUP_URI}" --endpoint-url="${S3_REGION_ENDPOINT}" | wc -l)
+      done
```
Comment (viktor-f) [inline helmfile/charts/sc-logs-retention/scripts/logs-retention.sh:57]: Add some comment here that explains why we have this loop (e.g. that it's necessary because not every cloud provider  is implementing the full s3 api), see the issue for inspiration.

File: helmfile/charts/sc-logs-retention/scripts/logs-retention.sh [hunk 2]
```diff
@@ -47,10 +47,23 @@ else
...
       BACKUP_URI="s3://${BUCKET_NAME}/logs/${BACKUP}"
-
+# As some providers have a fualty or incomplete implementation of the S3 API, a loop is needed in cases it's lacking
       echo "Deleting backup ${BACKUP_URI}"
-      aws s3 rm --recursive "${BACKUP_URI}" --endpoint-url="${S3_REGION_ENDPOINT}"
-    elif [[ ${GCS_BACKUP} == "true" ]]; then
+
+# Get the number of files currenctly avalible for deletion
+      NR_OF_FILES=$(aws s3 ls "${BACKUP_URI}" --endpoint-url="${S3_REGION_ENDPOINT}" | wc -l)
+# As long as their is files to be deleted, keep deleting them
```
Comment (viktor-f) [inline helmfile/charts/sc-logs-retention/scripts/logs-retention.sh:55]: Nit
```suggestion
# As long as there are files to be deleted, keep deleting them
```
You could also indent the comments to the same point as the code.
```suggestion
      # As long as there are files to be deleted, keep deleting them
```

**Review by viktor-f — APPROVED** [review]

File: helmfile/charts/sc-logs-retention/scripts/logs-retention.sh [hunk 3]
```diff
@@ -47,10 +47,23 @@ else
...
+        aws s3 rm --recursive "${BACKUP_URI}" --endpoint-url="${S3_REGION_ENDPOINT}"
+# Wait 5 seconds to see if new files have been created while the deletion was done
+        sleep 5
+        NR_OF_FILES=$(aws s3 ls "${BACKUP_URI}" --endpoint-url="${S3_REGION_ENDPOINT}" | wc -l)
+      done
+
+    elif
+
+      [[ ${GCS_BACKUP} == "true" ]]
+    then
```
Comment (Xartos) [inline helmfile/charts/sc-logs-retention/scripts/logs-retention.sh:66]:
```suggestion
    elif [[ ${GCS_BACKUP} == "true" ]]; then
```

File: helmfile/charts/sc-logs-retention/scripts/logs-retention.sh [hunk 4]
```diff
@@ -47,10 +47,23 @@ else
...
       echo "Deleting backup ${BACKUP_URI}"
-      aws s3 rm --recursive "${BACKUP_URI}" --endpoint-url="${S3_REGION_ENDPOINT}"
-    elif [[ ${GCS_BACKUP} == "true" ]]; then
+
+# Get the number of files currenctly avalible for deletion
+      NR_OF_FILES=$(aws s3 ls "${BACKUP_URI}" --endpoint-url="${S3_REGION_ENDPOINT}" | wc -l)
+# As long as their is files to be deleted, keep deleting them
+      while [ "$NR_OF_FILES" -gt 0 ]; do
+        aws s3 rm --recursive "${BACKUP_URI}" --endpoint-url="${S3_REGION_ENDPOINT}"
+# Wait 5 seconds to see if new files have been created while the deletion was done
```
Comment (Xartos) [inline helmfile/charts/sc-logs-retention/scripts/logs-retention.sh:58]: Indentation, same for all other comments as well
```suggestion
       # Wait 5 seconds to see if new files have been created while the deletion was done
```

**Review by Xartos — CHANGES_REQUESTED** [review]
Some minor stuff

File: helmfile/charts/sc-logs-retention/scripts/logs-retention.sh (hunk 2 above)
Comment (viktor-f) [reply helmfile/charts/sc-logs-retention/scripts/logs-retention.sh:55]: This still isn't fixed

**Review by Xartos — APPROVED** [review]
