### PR TITLE
Re-run Harbor init job after restore to ensure OIDC secrets synced

### LINKED ISSUE #2655: Harbor dex login doesn't work after disaster recovery
### Experienced behaviour

After performing [the restore steps for harbor](https://github.com/elastisys/compliantkubernetes-apps/tree/v0.47.2/restore/harbor), it was not possible to log in with Dex.

### Expected behaviour

It is possible to log in with Dex after restoring Harbor.

### Steps to reproduce

1. Perform restore steps for Harbor.
2. Go to `harbor.<domain>` and attempt to log in with Dex.

### Welkin Apps Version

v0.47.2

### Kubernetes Version

v1.31.9

### Additional context

Logs from Dex:

```
level=INFO msg="invalid client_secret on token request" client_id=harbor
```

### PR DESCRIPTION
**Pull request by Zash**
> [!warning]
> **This is a public repository, ensure not to disclose:**
>
> - [ ] personal data beyond what is necessary for interacting with this pull request, nor
> - [ ] business confidential information, such as customer names.

### What kind of PR is this?

**Required**: Mark one of the following that is applicable:

- [ ] kind/feature       
- [ ] kind/improvement   
- [ ] kind/deprecation   
- [ ] kind/documentation 
- [ ] kind/clean-up      
- [x] kind/bug           
- [ ] kind/other         

_Optional_: Mark one or more of the following that are applicable:

> [!important]
> Breaking changes should be marked `kind/admin-change` or `kind/dev-change` depending on type
> Critical security fixes should be marked with `kind/security`

- [ ] kind/admin-change   
- [ ] kind/dev-change     
- [ ] kind/security       
- [ ] [kind/adr](set-me\) 

### What does this PR do / why do we need this PR?

Harbor stores some configuration in its database.
When restoring from backups, that configuration is included.
This includes OIDC parameters.

This PR makes the Harbor restore script re-run the init job in case the OIDC secrets has been regenerated as part of disaster recovery.

- Fixes #2655

#### Information to reviewers

The last two commits changes from documenting the need to re-run the init job to always running the init job from the restore script.
If there's any reason not to always re-run the init job, those commits can easily be reverted.

#### How to test

1. Deploy at least Harbor and Dex to a service cluster
1. Wait for, or manually trigger a backup job
1. Change `.harbor.clientSecret` in `secrets.yaml` to a new random value
1. Apply change to Dex and Harbor
1. Follow [Harbor restore instructions](restore/harbor/README.md)
1. Try to login to Harbor

#### Checklist

- [x] Proper commit message prefix on all commits
    
- Change checks:
    - [x] The change is transparent
    - [ ] The change is disruptive
    - [x] The change requires no migration steps
    - [ ] The change requires migration steps
    - [ ] The change updates CRDs
    - [ ] The change updates the config _and_ the schema
- Documentation checks:
    - [ ] The [public documentation](https://github.com/elastisys/welkin) required no updates - (relevant documentation is in **this** repository, and updated herein)
    - [ ] The [public documentation](https://github.com/elastisys/welkin) required an update - [link to change](set-me\)
- Metrics checks:
    - [ ] The metrics are still exposed and present in Grafana after the change
    - [ ] The metrics names didn't change (Grafana dashboards and Prometheus alerts required no updates)
    - [ ] The metrics names did change (Grafana dashboards and Prometheus alerts required an update)
- Logs checks:
    - [x] The logs do not show any errors after the change
- PodSecurityPolicy checks:
    - [ ] Any changed Pod is covered by Kubernetes Pod Security Standards
    - [ ] Any changed Pod is covered by Gatekeeper Pod Security Policies
    - [ ] The change does not cause any Pods to be blocked by Pod Security Standards or Policies
- NetworkPolicy checks:
    - [ ] Any changed Pod is covered by Network Policies
    - [ ] The change does not cause any dropped packets in the NetworkPolicy Dashboard
- Audit checks:
    - [ ] The change does not cause any unnecessary Kubernetes audit events
    - [ ] The change requires changes to Kubernetes audit policy
- Falco checks:
    - [ ] The change does not cause any alerts to be generated by Falco
- Bug checks:
    - [ ] The bug fix is covered by regression tests

### CODE REVIEW

File: bin/harbor-restore.sh [hunk 1]
```diff
@@ -165,7 +165,10 @@ log_info "Cleaning up restore artifacts..."
 "${root_path}/bin/ck8s" ops kubectl sc delete -n harbor -f "${TMP_JOB_FILE}"
 "${root_path}/bin/ck8s" ops kubectl sc delete configmap -n harbor restore-harbor
 
+# Reinitialize
+"${root_path}/bin/ck8s" ops kubectl sc delete job -n harbor init-harbor-job
+"${root_path}/bin/ck8s" ops helmfile sc sync -l app=harbor
+
```
Comment (simonklb) [inline bin/harbor-restore.sh:171]: Maybe add a wait here to make sure the init job runs succesfully?

Comment (Zash) [reply bin/harbor-restore.sh:171]: Good idea

**Review by rarescosma — APPROVED** [review]
Very nice!

File: bin/harbor-restore.sh (hunk 1 above)
Comment (Zash) [reply bin/harbor-restore.sh]: https://github.com/elastisys/compliantkubernetes-apps/pull/2681/commits/ea6ea7114fe1026670195b60fb19c7777897d2c4

File: bin/harbor-restore.sh [hunk 2]
```diff
@@ -165,7 +165,11 @@ log_info "Cleaning up restore artifacts..."
 "${root_path}/bin/ck8s" ops kubectl sc delete -n harbor -f "${TMP_JOB_FILE}"
 "${root_path}/bin/ck8s" ops kubectl sc delete configmap -n harbor restore-harbor
 
+# Reinitialize
+"${root_path}/bin/ck8s" ops kubectl sc delete job -n harbor init-harbor-job
+"${root_path}/bin/ck8s" ops helmfile sc sync -l app=harbor
+"${root_path}/bin/ck8s" ops kubectl sc wait --for=condition=complete job -n harbor init-harbor-job --timeout=-1s
```
Comment (simonklb) [inline bin/harbor-restore.sh:171]: I believe that if the job's pod fails this will get stuck forever. Give it a decent amount of timeout instead? Perhaps with a "please check the logs using this command..." if it fails?

Comment (Zash) [reply bin/harbor-restore.sh]: 84885604

File: bin/harbor-restore.sh [hunk 3]
```diff
@@ -165,7 +165,13 @@ log_info "Cleaning up restore artifacts..."
 "${root_path}/bin/ck8s" ops kubectl sc delete -n harbor -f "${TMP_JOB_FILE}"
 "${root_path}/bin/ck8s" ops kubectl sc delete configmap -n harbor restore-harbor
 
+# Reinitialize
+log_info "Re-initializing..."
+"${root_path}/bin/ck8s" ops kubectl sc delete job -n harbor init-harbor-job
```
[the remark this answers is not in the document]
Comment (Zash) [reply bin/harbor-restore.sh]: https://github.com/elastisys/compliantkubernetes-apps/pull/2681/commits/f96d4d0e3a67e7ea08d673c39f39197e2800b13b

[the remark this answers is not in the document]
Comment (viktor-f) [reply bin/harbor-restore.sh]: Thanks, yes `--ignore-not-found` works.

If sync prompts it to just re-run the job regardless of if it has been deleted or not, then you can skip the delete command. But the delete command does not create any issues, so I'm ok with having it there.

**Review by viktor-f — APPROVED** [review]
