### PR TITLE
Fix GPU driver insufficient for CUDA runtime issue in operator v24.9.2

### LINKED ISSUE #2470: investigate the compatibility problem with GPU  operator v24.9.2
### Experienced behaviour

We go compatibility issues when testing out[ the newly upgraded GPU operator](https://github.com/elastisys/compliantkubernetes-apps/pull/2455). This is the error message on application pod trying to use GPU:
```
[Vector addition of 50000 elements]
Failed to allocate device vector A (error code CUDA driver version is insufficient for CUDA runtime version)!
```

### Expected behaviour

We should only need to enable gpu in `wc-config.yaml` and it should work fine without extra configuration.

### Steps to reproduce

1. Have a cluster on Elastx or Azure, and prepare a GPU node.
2. cherry-pick gpu-operator v24.9.2 from main branch.
3. Enable gpu in `wc-config.yaml` and install the operator. 
4. After the operator is installed successfully,[ deploy a test application](https://elastisys.io/welkin/user-guide/gpu/#deployment).

### Welkin Apps Version

v0.45.0 or v0.44.0

### Kubernetes Version

v1.30.9

### Additional context

We tested out on both Ubuntu 22.02 and Ubuntu 24.04, both have linux kernel 6.8.
Also tried out several different GPU driver versions that worked fine when installed by the older operator version, all led to same error.

Note that the contributor runs on kernel `5.14.0-503.22.1.el9_5.x86_64`. But I'm not sure if it's the kernel that makes the difference. It could also be some default configuration that does not work for our clusters.

### PR DESCRIPTION
**Pull request by HaoruiPeng**
add devicePlugin entry in default config to avoid templating error

> [!warning]
> **This is a public repository, ensure not to disclose:**
>
> - [ ] personal data beyond what is necessary for interacting with this pull request, nor
> - [ ] business confidential information, such as customer names.

### What kind of PR is this?

**Required**: Mark one of the following that is applicable:

- [ ] kind/feature       
- [ ] kind/improvement   
- [ ] kind/deprecation   
- [ ] kind/documentation 
- [ ] kind/clean-up      
- [x] kind/bug           
- [ ] kind/other         

_Optional_: Mark one or more of the following that are applicable:

> [!important]
> Breaking changes should be marked `kind/admin-change` or `kind/dev-change` depending on type
> Critical security fixes should be marked with `kind/security`

- [ ] kind/admin-change   
- [ ] kind/dev-change     
- [ ] kind/security       
- [ ] [kind/adr](set-me\) 

### What does this PR do / why do we need this PR?

1. Fixes #2470 

We had the following error reported from cuda-sample application when testing out the new gpu operator chart:
```
[Vector addition of 50000 elements]
Failed to allocate device vector A (error code CUDA driver version is insufficient for CUDA runtime version)!
```
This is actually caused by the environment variable `ACCEPT_NVIDIA_VISIBLE_DEVICES_ENVVAR_WHEN_UNPRIVILEGED` in CUDA container toolkit for some reason. Setting it to `true` fix the problem.

2. Cleaned-up default file `wc-config.yaml` as we have moved gpu configuration to `common-config.yaml` in apps v0.45.0
3. Also fixed a small issue in configuration, which would cause template err if devicePlugin is not set in `wc-config.yaml` under CK8S_CONFIG_PATH.
```
in /home/haorui/compliantkubernetes-apps/helmfile.d/state.yaml: failed processing release nvidia-gpu-operator: failed to render values files "values/gpu-operator.yaml.gotmpl": failed to render [values/gpu-operator.yaml.gotmpl], because of template: stringTemplate:31:14: executing "stringTemplate" at <.Values.gpu.devicePlugin>: map has no entry for key "devicePlugin"
``` 

#### Checklist

- [x] Proper commit message prefix on all commits
    
- Change checks:
    - [x] The change is transparent
    - [ ] The change is disruptive
    - [x] The change requires no migration steps
    - [ ] The change requires migration steps
    - [ ] The change updates CRDs
    - [ ] The change updates the config _and_ the schema
- Documentation checks:
    - [x] The [public documentation](https://github.com/elastisys/welkin) required no updates
    - [ ] The [public documentation](https://github.com/elastisys/welkin) required an update - [link to change](set-me\)
- Metrics checks:
    - [ ] The metrics are still exposed and present in Grafana after the change
    - [ ] The metrics names didn't change (Grafana dashboards and Prometheus alerts required no updates)
    - [ ] The metrics names did change (Grafana dashboards and Prometheus alerts required an update)
- Logs checks:
    - [ ] The logs do not show any errors after the change
- PodSecurityPolicy checks:
    - [ ] Any changed Pod is covered by Kubernetes Pod Security Standards
    - [ ] Any changed Pod is covered by Gatekeeper Pod Security Policies
    - [ ] The change does not cause any Pods to be blocked by Pod Security Standards or Policies
- NetworkPolicy checks:
    - [ ] Any changed Pod is covered by Network Policies
    - [ ] The change does not cause any dropped packets in the NetworkPolicy Dashboard
- Audit checks:
    - [ ] The change does not cause any unnecessary Kubernetes audit events
    - [ ] The change requires changes to Kubernetes audit policy
- Falco checks:
    - [ ] The change does not cause any alerts to be generated by Falco
- Bug checks:
    - [ ] The bug fix is covered by regression tests

### CODE REVIEW

**Comment by morguldir** [comment]
I'm not sure why the volume_mounts setup wasn't working for you :thinking: 

But it was also intended to prevent access to all((!) the GPUs from an unprivileged container, but it should have worked if you were requesting a GPU resource in the container https://docs.google.com/document/d/1zy0key-EL6JH50MZgwg96RPYxxXXnVUdxLZwGiyqLd8/edit

Changing the default might make sense though, but I'm curious about what went wrong, maybe the node wasn't using the nvidia runtime or something?

**Comment by HaoruiPeng** [comment]
> I'm not sure why the volume_mounts setup wasn't working for you 🤔
> 
> But it was also intended to prevent access to all((!) the GPUs from an unprivileged container, but it should have worked if you were requesting a GPU resource in the container https://docs.google.com/document/d/1zy0key-EL6JH50MZgwg96RPYxxXXnVUdxLZwGiyqLd8/edit
> 
> Changing the default here might make sense though, but I'm curious about what went wrong, maybe the node wasn't using the nvidia runtime or something?

I'm also curious why this didn't not work. But we didn't set it to `false` in the older version so it should be fine for now until we find out more info.

I also tried to install the driver and toolkit natively on the VM and tried to request the GPU from a container, got the same error. It could also due to some environment setup, but not quite clear yet. Thanks for pointing put the document! I will dig more when I have time.

**Comment by HaoruiPeng** [comment]
@kristiangronas Found the reason why. Actually very obvious :joy: 
We don't allow deploying privileged application pod in our clusters, so we need to accept unprivileged access to GPU drivers in the toolkit for welkin.
I thought the privileges are certain envvar settings specific to GPU, it turned out simply to be the privilege to the cluster.

**Comment by kristiangronas** [comment]
It's fine to run unprivileged applications, but they *need* to request the kubernetes resource, `VISIBLE_DEVICES=all` lets them bypass requesting it. when using `VISIBLE_DEVICES=volume-mounts`, it depends on the nvidia container runtime detecting the request, and making the GPU available as a volume mount

**Comment by kristiangronas** [comment]
<details>
  <summary>pod.yaml</summary>
  
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: cuda-vectoradd
  namespace: test
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
  restartPolicy: OnFailure

    #imagePullSecrets:
    #- name: mysecret
  containers:
  - name: cuda-vectoradd
    securityContext:
      privileged: false
      seccompProfile:
        type: "RuntimeDefault"
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    #command: ["/bin/sleep"]
    #args: ["4000"]
    image: "nvcr.io/nvidia/k8s/cuda-sample:devicequery-cuda11.7.1-ubuntu20.04"
      #image: "nvcr.io/nvidia/k8s/cuda-sample:nbody"
      #image: "itgit.app.uib.no:4567/kristian.gronas/a:cuda-12.8.0-devel-oraclelinux9"
    resources:
      limits:
        cpu: 100m
        nvidia.com/mig-3g.20gb.shared: 1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
            - key: elastisys.io/node-type
              operator: In
              values:
              - gpu
  tolerations:
    - effect: NoSchedule
      key: elastisys.io/node-type
      operator: Equal
      value: gpu

```

</details>

Then the other important part is that you need to use the nvidia containerd nvidia runtime (there's also a docker one if you're using that)
`sudo cat /etc/containerd/config.toml |grep default_runtime_name` should say nvidia

And then inspecting the container
```bash
ID=$(sudo /usr/local/bin/crictl ps --label "io.kubernetes.pod.name"="cuda-vectoradd" -a --output json |jq -r '.[] | first.id')
sudo /usr/local/bin/crictl inspect $ID | jq -r .info.runtimeOptions.binary_name
```
`/usr/local/nvidia/toolkit/nvidia-container-runtime`

You could also try this, but it worked without for us
```yaml
devicePlugin:
  env:
    ...
    - name: DEVICE_LIST_STRATEGY
      value: volume-mounts
```

**Comment by HaoruiPeng** [comment]
> pod.yaml
> Then the other important part is that you need to use the containerd nvidia runtime (there's also a docker one if you're using that) `sudo cat /etc/containerd/config.toml |grep default_runtime_name` should say nvidia
> 
> And then inspecting the container
> 
> ```shell
> ID=$(sudo /usr/local/bin/crictl ps --label "io.kubernetes.pod.name"="cuda-vectoradd" -a --output json |jq -r '.[] | first.id')
> sudo /usr/local/bin/crictl inspect $ID | jq -r .info.runtimeOptions.binary_name
> ```
> 
> `/usr/local/nvidia/toolkit/nvidia-container-runtime`
> 
> You could also try this, but it worked without for us
> 
> ```yaml
> devicePlugin:
>   env:
>     ...
>     - name: DEVICE_LIST_STRATEGY
>       value: volume-mounts
> ```

`DEVICE_LIST_STRATEGY=volume-mounts` did the magic! 
I did have the same pod specs as yours and the correct runtime path, still not sure what's wrong `envvar`  since the documentation says both should work fine. But pointing to the right device list path is indeed more helpful.
Thank you for the help! :raised_hands:  :heart_hands:

**Review by Pavan-Gunda — APPROVED** [review]
LGTM

**Comment by kristiangronas** [comment]
Glad we figured it out 🙏

File: helmfile.d/values/gpu-operator.yaml.gotmpl [hunk 1]
```diff
@@ -32,6 +32,24 @@ mig: {{- toYaml .Values.gpu.mig | nindent 2 }}
 devicePlugin: {{- toYaml .Values.gpu.devicePlugin | nindent 2 }}
```
Comment (Elias-elastisys) [inline helmfile.d/values/gpu-operator.yaml.gotmpl:32]: This can be removed right?

Comment (HaoruiPeng) [reply helmfile.d/values/gpu-operator.yaml.gotmpl:32]: I think it's good to have it there, as I allowed the option to customize devicePlungin configuration in `config/common-config.yaml`:

```
devicePlugin:
   config: {}
    #  default: "default"
    #  name: time-slicing-config-default
    #  create: true
    #  data:
    #    default: |-
    #      version: v1
    #      plugin:
    #        deviceListStrategy: "volume-mounts"
    #      flags:
    #        migStrategy: mixed
    #      migStrategy: mixed
    #      sharing:
    #        timeSlicing:
    #          renameByDefault: true
    #          failRequestsGreaterThanOne: true
    #          resources:
    #            - name: nvidia.com/gpu
    #              replicas: 2
    #            - name: nvidia.com/mig-3g.20gb
    #              replicas: 4
```

We usually don't use it, but this does allow customers to use more features in the operator, like time-slicing in the commented example.

Comment (HaoruiPeng) [reply helmfile.d/values/gpu-operator.yaml.gotmpl:32]: Aha you are right, that's supposed to be removed :joy: 
I didn't remember that I added the  new section for devicePlugin

**Review by Elias-elastisys — APPROVED** [review]
